In [3]:
import os
os.chdir("../")

In [5]:
import os
import pandas as pd

import awswrangler as wr
from helpers.datacleaning import drop_na, assign_region, extract_state, drop_bad_addresses, generate_sales_data, get_bean_data

#def process_sales_function(event, context):
source_df = wr.s3.read_csv(
    "s3://de-sales-data-project-raw-data-146479615822/Online_Shopping_Dataset.csv"
)

    #make daily data
df = generate_sales_data(source_df, "2025-01-01", "2025-02-28")

#format the date
#df['date'] = pd.to_datetime(df['date'], format='%m/%d/%Y').astype(str)
# df = date
df = drop_na(df)
df = drop_bad_addresses(df)
df = extract_state(df)
df = assign_region(df)
#df = wr.catalog.sanitize_dataframe_columns_names(df)   
table_name = "sales_data"
df.head()

,date,customer,address,bean_type,amount_purchased_lbs,purchase_cost,sell_price,profit,state,region
0,2025-01-01,Sienna Fork Healthy Eats,"1444 43rd Ave NE, Bismarck, ND",Anasazi Beans,987,987.0,3454.5,2467.5,ND,Mid-West
1,2025-01-01,El Pollo Loco,"907 W 5th St, Austin, TX",Split Peas,2748,549.6,1648.8,1099.2,TX,South West
2,2025-01-01,Native Foods,"808 5th Ave SE, Olympia, WA",Split Peas,2027,405.4,1216.2,810.8,WA,North West
3,2025-01-01,Ocotillo Agave Cantina,"2150 Hancock St, San Diego, CA",Great Northern Beans,1170,409.5,1228.5,819.0,CA,West
4,2025-01-01,Lentil & Greens,"1150 11th Ave, Helena, MT",Tepary Beans,4896,6364.8,22276.8,15912.0,MT,North West

In [3]:
df.head()

,date,customer,address,bean_type,amount_purchased_lbs,purchase_cost,sell_price,profit,state,region
0,2025-03-01,Sienna Fork Healthy Eats,"1444 43rd Ave NE, Bismarck, ND",Lentils,1577,441.56,1324.68,883.12,ND,Mid-West
1,2025-03-01,El Pollo Loco,"907 W 5th St, Austin, TX",Pinto Beans,7940,2382.00,7146.00,4764.00,TX,South West
2,2025-03-01,Hacienda Kitchen Smokehouse,"2276 N 3rd St, Baton Rouge, LA",Pinto Beans,2925,877.50,2632.50,1755.00,LA,South East
3,2025-03-01,Native Foods,"808 5th Ave SE, Olympia, WA",Lentils,891,249.48,748.44,498.96,WA,North West
4,2025-03-01,Ocotillo Agave Cantina,"2150 Hancock St, San Diego, CA",Black Beans,3010,963.20,2889.60,1926.40,CA,West

In [6]:
#show unique values for date
df['date'].unique()

array(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
       '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
       '2025-01-09', '2025-01-10', '2025-01-11', '2025-01-12',
       '2025-01-13', '2025-01-14', '2025-01-15', '2025-01-16',
       '2025-01-17', '2025-01-18', '2025-01-19', '2025-01-20',
       '2025-01-21', '2025-01-22', '2025-01-23', '2025-01-24',
       '2025-01-25', '2025-01-26', '2025-01-27', '2025-01-28',
       '2025-01-29', '2025-01-30', '2025-01-31', '2025-02-01',
       '2025-02-02', '2025-02-03', '2025-02-04', '2025-02-05',
       '2025-02-06', '2025-02-07', '2025-02-08', '2025-02-09',
       '2025-02-10', '2025-02-11', '2025-02-12', '2025-02-13',
       '2025-02-14', '2025-02-15', '2025-02-16', '2025-02-17',
       '2025-02-18', '2025-02-19', '2025-02-20', '2025-02-21',
       '2025-02-22', '2025-02-23', '2025-02-24', '2025-02-25',
       '2025-02-26', '2025-02-27', '2025-02-28'], dtype=object)

In [4]:
#source_df.head()

NameError: name 'source_df' is not defined

In [7]:
wr.s3.to_parquet(
        df, 
        path = f"s3://de-sales-data-project-data-lake-146479615822/{table_name}/",
                dataset=True,
                table=table_name,
                database="data_lake",
                mode="overwrite_partitions",
                partition_cols=["date"],
                )

{'paths': ['s3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-01/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-02/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-03/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-04/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-05/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-06/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-07/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-08/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-09/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-10/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-11/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-12/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-13/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-14/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-15/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-16/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-17/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-18/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-19/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-20/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-21/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-22/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-23/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-24/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-25/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-26/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-27/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-28/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-29/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-30/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-31/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-01/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-02/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-03/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-04/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-05/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-06/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-07/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-08/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-09/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-10/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-11/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-12/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-13/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-14/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-15/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-16/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-17/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-18/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-19/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-20/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-21/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-22/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-23/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-24/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-25/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-26/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-27/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet',
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-28/c62b63f194e24b009d5d5514e8aebb5e.snappy.parquet'],
 'partitions_values': {'s3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-01/': ['2025-01-01'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-02/': ['2025-01-02'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-03/': ['2025-01-03'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-04/': ['2025-01-04'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-05/': ['2025-01-05'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-06/': ['2025-01-06'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-07/': ['2025-01-07'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-08/': ['2025-01-08'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-09/': ['2025-01-09'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-10/': ['2025-01-10'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-11/': ['2025-01-11'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-12/': ['2025-01-12'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-13/': ['2025-01-13'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-14/': ['2025-01-14'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-15/': ['2025-01-15'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-16/': ['2025-01-16'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-17/': ['2025-01-17'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-18/': ['2025-01-18'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-19/': ['2025-01-19'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-20/': ['2025-01-20'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-21/': ['2025-01-21'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-22/': ['2025-01-22'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-23/': ['2025-01-23'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-24/': ['2025-01-24'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-25/': ['2025-01-25'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-26/': ['2025-01-26'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-27/': ['2025-01-27'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-28/': ['2025-01-28'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-29/': ['2025-01-29'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-30/': ['2025-01-30'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-01-31/': ['2025-01-31'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-01/': ['2025-02-01'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-02/': ['2025-02-02'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-03/': ['2025-02-03'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-04/': ['2025-02-04'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-05/': ['2025-02-05'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-06/': ['2025-02-06'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-07/': ['2025-02-07'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-08/': ['2025-02-08'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-09/': ['2025-02-09'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-10/': ['2025-02-10'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-11/': ['2025-02-11'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-12/': ['2025-02-12'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-13/': ['2025-02-13'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-14/': ['2025-02-14'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-15/': ['2025-02-15'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-16/': ['2025-02-16'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-17/': ['2025-02-17'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-18/': ['2025-02-18'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-19/': ['2025-02-19'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-20/': ['2025-02-20'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-21/': ['2025-02-21'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-22/': ['2025-02-22'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-23/': ['2025-02-23'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-24/': ['2025-02-24'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-25/': ['2025-02-25'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-26/': ['2025-02-26'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-27/': ['2025-02-27'],
  's3://de-sales-data-project-data-lake-146479615822/sales_data/date=2025-02-28/': ['2025-02-28']}}